import Link from "next/link";
import { ProjectGrid } from "./project-grid";
const skillGroups=[{label:"Data",value:"SQL · Excel · Pandas · NumPy · Spark · Hadoop · Hive"},{label:"Statistical",value:"Regression · Clustering · Forecasting · Anomaly Detection · Hypothesis Testing"},{label:"Visualization",value:"Tableau · Power BI · Matplotlib · Seaborn · Plotly Dash"},{label:"Machine Learning",value:"Scikit-learn · XGBoost · NLP · RAG · LoRA/QLoRA · Computer Vision"},{label:"Tools",value:"Git · Jira · Dataiku · FastAPI · Gradio · Microsoft Office"}];
export default function Home(){return <main>
<nav className="nav shell" aria-label="Primary navigation"><Link className="wordmark" href="#top">SB<span>.</span></Link><div className="nav-links"><Link href="#work">Work</Link><Link href="#experience">Experience</Link><Link href="#leadership">Leadership</Link><Link href="#about">About</Link><Link className="nav-cta" href="/resume">Résumé <span>↗</span></Link></div></nav>
<section className="hero shell" id="top"><div className="hero-kicker"><i/> Parlin, New Jersey · Open to opportunities</div><div className="hero-grid"><div><p className="eyebrow">DATA ANALYST · ML PRACTITIONER</p><h1>Turning complex data into <em>clear direction.</em></h1></div><div className="hero-aside"><p>I build reliable analysis, decision-ready dashboards, and practical machine learning systems across finance, healthcare, and operations.</p><a className="text-link" href="#work">Explore selected work <span>↓</span></a></div></div><div className="data-stage" aria-label="Abstract data visualization"><div className="orb orb-one"/><div className="orb orb-two"/><div className="stage-copy"><span>01 / PROFILE</span><strong>SAMPSON<br/>BOATENG</strong></div><div className="axis axis-x"/><div className="axis axis-y"/>{[18,32,47,61,74,86].map((left,i)=><span key={left} className="data-point" style={{left:`${left}%`,top:`${70-(i%3)*18}%`}}/>)}<div className="stage-note">M.S. Applied Machine Intelligence<br/>B.S. Computer Science</div></div></section>
<section className="section shell" id="work"><div className="section-head"><div><p className="eyebrow">02 / SELECTED WORK</p><h2>Projects with<br/><em>measurable depth.</em></h2></div><p>Click any project to step inside the problem, approach, tools, and outcome.</p></div><ProjectGrid/></section>
<section className="section shell experience" id="experience"><div className="section-head compact"><div><p className="eyebrow">03 / EXPERIENCE</p><h2>Analysis grounded<br/>in <em>real operations.</em></h2></div></div><div className="timeline"><article><div className="timeline-meta"><b>2025 — PRESENT</b><span>New York, NY</span></div><div><h3>Finance, Development & IT Administration Support Analyst</h3><h4>Village Health Works</h4><p>Analyze financial and donor data, investigate discrepancies, prepare forecasts and management reporting, and establish data-quality standards that improve trust in organizational records.</p></div></article><article><div className="timeline-meta"><b>2021 — 2023</b><span>Saratov, Russia</span></div><div><h3>Programmer Intern</h3><h4>Bosch Techno-Engineering Ltd</h4><p>Supported development and QA cycles, diagnosed defects, helped improve system stability by 20%, and built an internal encryption and decryption testing utility.</p></div></article></div></section>
<section className="section shell leadership" id="leadership"><div className="section-head"><div><p className="eyebrow">04 / LEADERSHIP & RECOGNITION</p><h2>Building community<br/>with <em>purpose.</em></h2></div><p>Leadership shaped by service, inclusion, and a commitment to making campus life more connected.</p></div><div className="leadership-grid"><article className="role-card"><span>01</span><h3>Student Ambassador</h3><h4>Northeastern University · The Roux Institute</h4><ul><li>Represented the student experience for prospective and incoming students through campus programs and community events.</li><li>Welcomed new students, shared peer guidance, and helped strengthen connections across the Roux community.</li></ul></article><article className="role-card"><span>02</span><h3>Founder, Roux Pickup Sports</h3><h4>The Roux Institute</h4><ul><li>Founded an inclusive recreational sports community that created consistent opportunities for students to connect outside the classroom.</li><li>Organized games, coordinated participation, and built a welcoming environment across programs and experience levels.</li></ul></article><article className="role-card"><span>03</span><h3>Executive Member</h3><h4>Data for Social Good (DSG)</h4><ul><li>Supported one of the campus’s leading student interest groups focused on applying data skills to meaningful social challenges.</li><li>Contributed to group strategy, programming, student engagement, and collaborative initiatives connecting analytics with community impact.</li></ul></article></div><article className="award-card"><div className="award-mark"><b>100</b><span>LAUREL<br/>& SCROLL</span></div><div><p className="eyebrow">UNIVERSITY RECOGNITION</p><h3>Laurel and Scroll 100 Award</h3><h4>Northeastern University</h4><p>Recognized among 100 students for outstanding achievement across academics, leadership, and meaningful student engagement.</p></div></article></section>
<section className="section shell" id="about"><div className="about-grid"><div><p className="eyebrow">05 / CAPABILITIES</p><h2>A practical toolkit for <em>better decisions.</em></h2><p className="about-copy">From raw records to an executive-ready narrative, I care about accuracy at every step: cleaning, validation, exploration, modeling, visualization, and documentation.</p></div><div className="skill-list">{skillGroups.map((s,i)=><div key={s.label}><span>0{i+1}</span><h3>{s.label}</h3><p>{s.value}</p></div>)}</div></div></section>
<section className="education shell"><p className="eyebrow">06 / EDUCATION</p><div className="education-grid"><article><span>2025</span><h3>Master of Science</h3><p>Applied Machine Intelligence</p><b>Northeastern University<br/>The Roux Institute</b></article><article><span>2023</span><h3>Bachelor of Science</h3><p>Computer Science</p><b>Saratov State University</b></article></div></section>
<footer className="footer"><div className="shell"><p className="eyebrow">LET&apos;S WORK TOGETHER</p><h2>Have a data problem<br/>worth <em>solving?</em></h2><a className="email" href="mailto:samboateng190@gmail.com">samboateng190@gmail.com ↗</a><div className="footer-row"><p>© 2026 Sampson Boateng</p><div><a href="https://github.com/Boatengs" target="_blank" rel="noreferrer">GitHub</a><a href="https://linkedin.com/in/sam-boateng" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://huggingface.co/samurvivor-07" target="_blank" rel="noreferrer">Hugging Face</a><a href="tel:+12073325395">(207) 332-5395</a></div></div></div></footer>
</main>}
